version: "3"
services: 
  reverseproxy:
    image: s4g3/reverseproxy:v3 
    ports:
     - 8080:8080 
    restart: always 
    depends_on: 
      - backend-user
      - backend-feed 
  backend-user: 
    image: s4g3/udagram-api-user:v3 
    environment: 
      POSTGRES_USERNAME: $POSTGRES_USERNAME 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET 
      JWT_SECRET: $JWT_SECRET 
      URL: "http://localhost:8100" 
  backend-feed: 
    image: s4g3/udagram-api-feed:v3 
    volumes: 
    - $HOME/.aws:/root/.aws 
    environment: 
      POSTGRES_USERNAME: $POSTGRES_USERNAME 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET 
      JWT_SECRET: $JWT_SECRET 
      URL: "http://localhost:8100" 
  frontend: 
    image: s4g3/udagram-frontend:v3
    ports: 
    - "8100:80" 