version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: s4g3/reverseproxy:v5
  backend_user:
    build:
      context: ./udagram-api-user
    image: s4g3/udagram-api-user:v5
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: s4g3/udagram-api-feed:v5
  frontend:
    build:
      context: ./udagram-frontend
    image: s4g3/udagram-frontend:v5