apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    Deployment: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: s4g3/udagram-frontend:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080